### ISSUE TITLE
Categories not showing up in analyzing tools (ReSharper)

### ISSUE THREAD

**Issue by Wolfsblvt** [brendanconnolly/Xunit.Categories#1]
Heya.
I really like your idea to make using categories easier. I tried it out and I would love to use it, but there is one big issue with it.

Discovering the tests on command line works fine. But I am running tests mostly with ReSharper, in Continuous Testing Session or by running them manually.
The Tests are grouped there when I am using `[Trait("Category", "Bug")]` manually.
![image](https://cloud.githubusercontent.com/assets/9962104/26824851/3054a634-4ab3-11e7-9306-a4f38271f2f7.png)

It does not work with your new Attributes:
![image](https://cloud.githubusercontent.com/assets/9962104/26824887/4ced5d4a-4ab3-11e7-8be2-5e6fc67bc528.png)

Do you know if there is any way to get this to work?

**Comment by brendanconnolly** [comment]
This is because the resharper test runner uses an older model for discovering traits. xUnit shifted to using the trait discoverer pattern and resharper has not updated their runner. I use resharper as well and its definitely less than ideal.  

You can add your voice to the issue below if you like maybe JetBrains will listen
[https://youtrack.jetbrains.com/issue/RSRP-458779](https://youtrack.jetbrains.com/issue/RSRP-458779)

**Comment by Wolfsblvt** [comment]
Thank for your response. I have added a comment and voted for this issue. Let's hope that Jetbrains will do that some time in the future.
